snd-soc-aw881xx-objs += aw881xx.o
snd-soc-aw881xx-objs += aw881xx_monitor.o
snd-soc-aw881xx-objs += aw881xx_cali.o
snd-soc-aw881xx-objs += aw881xx_spin.o
obj-$(CONFIG_SND_SOC_AW881XX) += snd-soc-aw881xx.o

