subdir-ccflags-y += -Werror -I$(srctree)/sound/soc/mediatek/common

#for AWINIC AW882XX Smart PA
obj-$(CONFIG_SND_SMARTPA_AW882XX) := snd-soc-aw882xx.o

snd-soc-aw882xx-objs += aw882xx.o
snd-soc-aw882xx-objs += aw882xx_monitor.o
snd-soc-aw882xx-objs += aw882xx_init.o
snd-soc-aw882xx-objs += aw882xx_dsp.o
snd-soc-aw882xx-objs += aw882xx_device.o
snd-soc-aw882xx-objs += aw882xx_calib.o
snd-soc-aw882xx-objs += aw882xx_bin_parse.o
snd-soc-aw882xx-objs += aw882xx_spin.o
